/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ConexionBD;

/**
 *
 * @author DELL
 */
public class NInicio extends javax.swing.JFrame {
    ConexionBD con = new ConexionBD();
    Connection cn = con.Conexion();
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    int idc;
    
    /**
     * Creates new form NInicio
     */
    
    void Nuevo(){
        nombretxt.setText("");
        directxt.setText("");
    }
    
    void LimpiarTabla() {
        for(int i = 0; i < Tabla.getRowCount(); i++){
            modelo.removeRow(i);
            i = i-1;
        }
        for(int j = 0; j < Tabla2.getRowCount(); j++){
            modelo2.removeRow(j);
            j = j -1;
        }
        Nuevo();
    }
    
    void totalPiezas(){
        try {
            String sql = "SELECT Cod_Sucursal, SUM(Stock) AS Total_Piezas FROM productos GROUP BY Cod_Sucursal";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Object[] cli = new Object[2];
            modelo2 = (DefaultTableModel) Tabla2.getModel();
            while (rs.next()) {
                cli [0] = rs.getInt("Cod_Sucursal");
                cli [1] = rs.getString("Total_Piezas");
                
                modelo2.addRow(cli);
            }
            
            Tabla2.setModel(modelo2);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }
    
    void consulta() {
        try {
            String sql = "SELECT * FROM sucursales";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Object[] cliente = new Object[3];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                cliente [0] = rs.getInt("ID_Sucursal");
                cliente [1] = rs.getString("Nom_Sucursal");
                cliente [2] = rs.getString("Direccion");
                
                modelo.addRow(cliente);
            }
            
            Tabla.setModel(modelo);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
        
    }
    
    public NInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        consulta();
        totalPiezas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        nombretxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        directxt = new javax.swing.JTextField();
        AGREGAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        codPiezatxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cedulatxt = new javax.swing.JTextField();
        BUSCAR_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Sucursal", "Nombre", "Direccion"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setText("Direccion:");

        directxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directxtActionPerformed(evt);
            }
        });

        AGREGAR.setText("AGREGAR");
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setText("Codigo Pieza:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel7.setText("Cedula:");

        BUSCAR_.setText("Buscar");
        BUSCAR_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_ActionPerformed(evt);
            }
        });

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Sucursal", "Total Piezas"
            }
        ));
        jScrollPane2.setViewportView(Tabla2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("RECARGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPiezatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR_)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(directxt, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(directxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(codPiezatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Buscar)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(cedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(BUSCAR_))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        String title = "";
        if (fila == -1){
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila, 0).toString());
            title = (String) Tabla.getValueAt(fila, 1);
        }
        Plantilla pln = new Plantilla(title, idc);
        pln.setVisible(true);
    }//GEN-LAST:event_TablaMouseClicked

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void directxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directxtActionPerformed

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed
        // TODO add your handling code here:
        String nombre = nombretxt.getText();
        String direccion = directxt.getText();

        try {
            if(nombre.equals("") || direccion.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan por ingresar datos");
            } else {
                String sql = "INSERT INTO `sucursales`( `Nom_Sucursal`, `Direccion`) VALUES ('"+nombre+"','"+direccion+"')";
                PreparedStatement ps = cn.prepareCall(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Se guardaron correctamente los datos");
                LimpiarTabla();
                consulta();
                totalPiezas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_AGREGARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        try {
            if (fila<0) {
                JOptionPane.showMessageDialog(null, "Cliente no seleccionado");
                LimpiarTabla();
                consulta();
                totalPiezas();
            } else {
                String sqlProductos = "DELETE FROM productos WHERE Cod_Sucursal='" + idc + "'";
                String sqlSucursales = "DELETE FROM sucursales WHERE ID_Sucursal='" + idc + "'";
                PreparedStatement psProductos = cn.prepareCall(sqlProductos);
                PreparedStatement psSucursales = cn.prepareCall(sqlSucursales);
                psProductos.executeUpdate();
                psSucursales.executeUpdate();
                JOptionPane.showMessageDialog(null, "Dato borrado correctamente");
                LimpiarTabla();
                consulta();
                totalPiezas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here
        String codPieza = codPiezatxt.getText();
        int cantidad = 0;
        String name = "";
        try {
            String sql = "SELECT * FROM productos WHERE Cod_Pieza='"+codPieza+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
 
            while (rs.next()) {
                name = rs.getString("Nombre");
                cantidad += rs.getInt("Stock");
            }
            JOptionPane.showMessageDialog(null, "Producto: "+name+"\nStock: "+cantidad);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BUSCAR_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR_ActionPerformed
        // TODO add your handling code here:
        int cedula = Integer.parseInt(cedulatxt.getText());
        String doc_iden = "";
        String nombres = "";
        String apellidos = "";
        int suclab = 0;
        int tipo = 0;
        String rol = "";
        try {
            String sql = "SELECT * FROM usuarios WHERE Doc_ident='"+cedula+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
 
            while (rs.next()) {
                doc_iden = rs.getString("Doc_ident");
                nombres = rs.getString("Nombres");
                apellidos = rs.getString("Apellidos");
                suclab = rs.getInt("Suc_Lab");
                tipo = rs.getInt("ID_Rol");
            }
            if(tipo==1){
                rol = "Administrador";
            } else {
                rol = "Vendedor";
            }
            JOptionPane.showMessageDialog(null, "Documento: "+doc_iden+"\nNombres: "+nombres+"\nApellidos: "+apellidos+"\nID Sucursal donde labura: "+suclab+"\nRol: "+rol);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_BUSCAR_ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        totalPiezas();
        consulta();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JButton BUSCAR_;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTextField cedulatxt;
    private javax.swing.JTextField codPiezatxt;
    private javax.swing.JTextField directxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombretxt;
    // End of variables declaration//GEN-END:variables
}
